### ISSUE TITLE
4.6 readyness

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.bic#11]
With the 4.6 in beta since today i was wondering, do you foresee any issues with compatibility (or would you think this extension will have no big issues working in 4.6? Of course I will also try and test myself, but you know the architecture of the extension and changes in civicrm better than I do :-)

**Comment by systopia** [comment]
@magnolia61 We currently don't have time/funding to do 4.6 compatibility. Just give it a try, and let us know your findings.

**Comment by michau** [comment]
@magnolia61 @systopia FYI - I'm using org.project60.bic on 4.6.5 sandbox install without any noticeable problems. Two pull requests recently submitted (https://github.com/Project60/org.project60.bic/pull/17 and https://github.com/Project60/org.project60.bic/pull/19) were developed and tested on this version. 

Did have some problems with German bank list update (partial update message), but that seems to be limited to parser/source.

**Comment by systopia** [comment]
> Did have some problems with German bank list update (partial update message), but that seems to be limited to parser/source.

Yes, that should depend on your PHP's ``max_execution`` timeout.

**Comment by systopia** [comment]
I think a lot of people (including us) are using this on 4.6 now without any troubles. I'll just close this.
