### ISSUE TITLE
Belgian parser stopped working

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.bic#12]
Error message as expected:
> Couldn't download data file. You either have no internect connection, or the extension is outdated. In this case, please contact us.

**Comment by tttp** [comment]
and closing ;)

**Comment by systopia** [comment]
> and closing ;)
...still testing if there's an impact on the other parsers :)

**Comment by systopia** [comment]
Everything seems to work fine, except the ES parser. But that seems to be another problem, see https://github.com/Project60/org.project60.bic/issues/14
