### ISSUE TITLE
Spanish parser not working any more

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.bic#14]
The reason is, that in the list we use (http://www.bde.es/f/webbde/IFI/servicio/regis/ficheros/es/REGBANESP_CONESTAB_A.XLS), they removed the `BIC` column...

**Comment by systopia** [comment]
I added an error message with https://github.com/Project60/org.project60.bic/commit/90631d7a0cf746b12ac124dc53e16d0674981c58#diff-54af829263c19b58d8112d7a3f01b95eR65.

But we still need to fix it. @elcapo could you look into this?

**Comment by systopia** [comment]
@helenagarcia90 will take care of this :)

**Comment by tttp** [comment]
Hi,

We have a separate implementation: a scraper that uses another source (in python) and generate a csv+ a new spanish parser.

on the pro side: it's easy to use the same tool for other countries (we've done uk and a bunch of others, I'll check to add lux too)

**Comment by systopia** [comment]
@tttp: Link?

**Comment by systopia** [comment]
> I found this https://github.com/PeterNotenboom/SwiftCodes. Maybe we could use it as default BIC source for all country BIC codes allowing overwrite country BIC source when it is prefereable.

@francescbassas: That's a cool project!

The problem with this data is, that it doesn't have the national bank id. This national ID is usually part of the IBAN, and with that information missing we cannot infer the BIC from a given IBAN.

**Comment by sluc23** [comment]
we haven't found a valid public source of Spanish Bank Swift List online, which is not a surprise because SEPA in Spain still very undocumented 
But we have our own list we completed along past years, it's pretty complete.. should we publish it somewhere online and use it as the reference for the extension?

**Comment by bjendres** [comment]
> should we publish it somewhere online and use it as the reference for the extension?

Absolutely yes :) (That's what I meant to say with the "thumbs up") Let me know when you have a publicly accessible link.

**Comment by sluc23** [comment]
> > should we publish it somewhere online and use it as the reference for the extension?
> 
> Absolutely yes :) (That's what I meant to say with the "thumbs up") Let me know when you have a publicly accessible link.

any ideas where i can publish this file? A Github repo maybe :thinking:  ?

**Comment by bjendres** [comment]
> any ideas where i can publish this file? A Github repo maybe thinking ?

Sure, whatever works for you. But please make sure that there's no legal issues publishing this data, we don't want anyone to get into trouble.

**Comment by RastaTux** [comment]
@sluc23 Any progression here? I would also be interested in such a list. Or are there legal issues?

**Comment by sluc23** [comment]
@RastaTux to be honest i'm not sure if there's any legal issue. I cannot find any list like this in internet, which is weird, because it's only public information about banks.. so not sure how to move forwards from here..

**Comment by RastaTux** [comment]
@sluc23 I see.. I'm no laywer but if you collected these information from public sources, serving them collected shouldn't be a problem in my eyes.

**Comment by sluc23** [comment]
We decided to publish our list of Spanish Banks' Bic/Swift codes in a public Github repo here: https://github.com/ixiam/sepa_bic
Please anyone feel free to contribute updating/adding this file.
So far is only for **ES**, but it's open to add any other country if there's a similar situation than Spain, where there's no public access to this information in the web..

I'll push a PR soon to use this list form Spanish Banks in org.project60.bic extension

**Comment by sluc23** [comment]
https://github.com/Project60/org.project60.bic/pull/51
