### ISSUE TITLE
Luxemburg parser stopped working

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.bic#16]
again, the bank has probably pulled the document we rely on...

**Comment by tttp** [comment]
same comment than for spain: we have something working, but needs python+a scraper

**Comment by systopia** [comment]
@tttp: Link?

**Comment by eth4ever** [comment]
The LU bank list is available from: https://www.abbl.lu/content/uploads/2017/12/IBAN_BIC_CODES_LUX_20180329.xlsx
change line 25 of org.project60.bic/CRM/Bic/Parser/LU.php
It works for me but I don't how to fix it on GITHUB.

**Comment by kainuk** [comment]
Thanks @eth4ever , created a PR https://github.com/Project60/org.project60.bic/pull/35

**Comment by systopia** [comment]
seems to work, released with ``1.3.beta1``
