### ISSUE TITLE
Austrian parser has incomplete data

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.bic#24]
The source the Austrian parser uses is incomplete and probably not up to date. Examples for missing Banks:
- BLZ: 60000 IBAN: AT696000000092159385 (public)
- BLZ: 19043 IBAN: AT611904300234573201 (public example)

**Comment by systopia** [comment]
Is now being tested.

**Comment by bjendres** [comment]
Switched to a new source, and update parser.

IBAN ``AT696000000092159385`` is now resolved, the other one isn't.

@pfigel could you confirm that this is update makes sense?
