### ISSUE TITLE
what about changing the hide BIC UI?

### ISSUE THREAD

**Issue by tttp** [Project60/org.project60.bic#27]
Hi,

so right now, you have an option to hide the BIC field when you can find it from the IBAN. What about changing that workflow so it's hidden by default and show if we can't find it?

Rationale: less fields by default, less scary.

**Comment by systopia** [comment]
Sure, if you're talking about changing the default value to ``true``, be my guest :)

However, we should make sure the behaviour doesn't change for people that simply upgrade to a new version...

**Comment by tttp** [comment]
so that would be adding a different setting
hide if found (existing one)
hide by default (new one)

**Comment by systopia** [comment]
I don't get the difference. If the current setting is enabled, it will hide by default, and show it only if the BIC couldn't be found. What would the extra setting do?

**Comment by bjendres** [comment]
closed for inactivity - please re-open if problem still exists
