### ISSUE TITLE
Dutch parser not working any more

### ISSUE THREAD

**Issue by systopia** [Project60/org.project60.bic#29]

**Comment by eth4ever** [comment]
There is a BIC list of Dutch banks at: https://www.betaalvereniging.nl/aandachtsgebieden/giraal-betalingsverkeer/bic-sepa-transacties/

Is it possible to implement this list in the LittleBic extension in order to make it work for the Dutch Banks again?

**Comment by systopia** [comment]
Thanks for the information @eth4ever 

The list format looks o.k., but does the Netherlands really only have 70 registered banks?

**Comment by kainuk** [comment]
PR https://github.com/Project60/org.project60.bic/pull/34
