### ISSUE TITLE
support for Polish banks

### ISSUE THREAD

**Issue by rzylla** [Project60/org.project60.bic#31]
support for Polish banks  is no longer valid  from Sept 1 2017.
Needs new link to  dz_bank_jorg.txt

**Comment by michau** [comment]
File is available for download here: https://ewib.nbp.pl/faces/pages/daneDoPobrania.xhtml

Unfortunately, it's not available for GET download anymore. For some (stupid) reason, file download is being done via POST request, and that's not trivial to implement.

A quick workaround would be to download the file from above link and change line 26 in CRM/Bic/Parser/PL.php to downloaded file path on the same machine as CiviCRM install, e.g.

static $page_url = '/var/www/civicrm/sites/default/files/civicrm/upload/dz_bank_jorg.txt';

This should do the trick.

**Comment by systopia** [comment]
seems to work, released with ``1.3.beta1``
