### ISSUE TITLE
Check for "navID" being set in bic_navhelper_get_max_nav_id

### ISSUE THREAD

**Issue by jensschuppe** [Project60/org.project60.bic#32]
PHP notices "Undefined index: navID in bic_navhelper_get_max_nav_id" are being thrown while crawling the menu tree for finding the maximum navID for  items in the navigation menu tree when there are menu items without a navID set.

Not sure whether this stems from incorrect implementations in other extensions (i.e. them not setting a "navID" attribute for a menu item), but it's quite annoying when this happens.

There should be a check for whether the "navID" attribute exists in `bic_navhelper_get_max_nav_id` within `$max_id = max($max_id, $entry['attributes']['navID']);`, e.g. `    $max_id = (isset($entry['attributes']['navID']) ? max($max_id, $entry['attributes']['navID']) : 0);`.

**Comment by systopia** [comment]
PRs welcome :)

**Comment by kainuk** [comment]
PR https://github.com/Project60/org.project60.bic/pull/33

**Comment by systopia** [comment]
Thanks, seems to work, released with ``1.3.beta1``
