### ISSUE TITLE
Lookup of german BIC's has changed (again)

### ISSUE THREAD

**Issue by Detsieber** [Project60/org.project60.bic#40]
The Bundesbank again has changed the format, so that the previous code of the parser (DE.php) doesn't work anymore:
- file name has changed
- - format of PLAIN file has changed to UTF8 - and moreover, even with the correct encoding, in some cases fixed record calculation produces errors when Umlaute are occuring in the bank name.

The Bundesbank offers a download option as xlsx-file, so I changed the code of DE.php accordingly, taking NL.php and ES.php as a sample. 

The Code is tested and works fine, and I will upload it immediately.

**Comment by bjendres** [comment]
released with ``1.4-beta1``
