### ISSUE TITLE
PHP deprecated

### ISSUE THREAD

**Issue by wintermoor** [Project60/org.project60.bic#49]
Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/html/test/wp-content/uploads/civicrm/ext/org.project60.bic-master/bic.civix.php on line 247

**Comment by bjendres** [comment]
yes, i guess you have to regenerate ``bic.civix.php``, could you provide a PR? Which PHP version are you using?

**Comment by wintermoor** [comment]
PHP 7.4.3
