### ISSUE TITLE
Link won't work

### ISSUE THREAD

**Issue by wintermoor** [Project60/org.project60.bic#50]
https://github.com/Project60/org.project60.bic/blob/master/templates/CRM/Bic/Page/BicList.tpl#L16 
L140
L173

<a **href='bicImport'**>update your bank list</a> 
does not work with my WordPress, but I'm unsure how to fix it. 
/wp-admin/admin.php?page=CiviCRM&q=civicrm%2FbicImport is working, but not good for Drupal or WP with CleanURl. 

Not very important...

**Comment by bjendres** [comment]
Can anyone reproduce this on wordpress?

**Comment by eptbertram** [comment]
This issue seems to be solved on Little BIC ext, v. 1.8.3. idk how...

**Comment by vurt2** [comment]
I can confirm the problem with the "bicList" link using wordpress. The link is relative (to "bicList") in template Config.tpl - which leads to "/wp-admin/bicList ". It could be fixed by making it absolute to "/civicrm/bicList".

**Comment by vurt2** [comment]
@bjendres Yes, it works fine now. Thank you very much!

**Comment by wintermoor** [comment]
Issue solved, thank you. It sends you to frontend, but it sends you. Issue may be closed now.

**Comment by bjendres** [comment]
Thanks!
