### ISSUE TITLE
German Parser not working any more

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.bic#53]
@jojowork found, that the German parser is not working any more (i.e. the file is gone), but that -most likely- the new file is [this](https://www.bundesbank.de/resource/blob/602632/d025696e366a91063fb307cc1f73e0d5/mL/blz-aktuell-txt-data.txt).

**Comment by bjendres** [comment]
@jojowork could you confirm that this is really the issue? This still works locally for me...

**Comment by lbl-knts** [comment]
`http://www.bundesbank.de/Redaktion/DE/Standardartikel/Aufgaben/Unbarer_Zahlungsverkehr/bankleitzahlen_download.html` is error 404. new page could be`https://www.bundesbank.de/de/aufgaben/unbarer-zahlungsverkehr/serviceangebot/bankleitzahlen/download-bankleitzahlen-602592` but there are many available downloads.

**Comment by bjendres** [comment]
Thanks for reporting, @lbl-knts, but I can't reproduce this. In version ``1.6`` the current source for the German BIC data is ``https://www.bundesbank.de/resource/blob/602630/1b5138f22cc648106b16a29ecc3117c1/mL/blz-aktuell-xls-data.xlsx``, which seems seems to run fine, and I can access it through a browser as well.

Are you sure you've upgrade to the latest LittleBIC version (``1.6``)?

**Comment by lbl-knts** [comment]
oh, my fault, i have downloaded the latest version from here: https://civicrm.org/de/extensions/little-bic-extension it is 1.2. 
Thanks, @bjendres. i will update the ext.

**Comment by bjendres** [comment]
Oh, thanks for pointing this out, I thought that after being flagged as ``reviewed`` it would automatically pick up on new releases. I created #59 for that. Thank you!
