### ISSUE TITLE
Notice problem on navigationmenu

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.bic#6]
Using civicrm 4.5.5./Drupal 7.3.4 together with the current dev_pp of civisepa I get:

Notice: Undefined variable: new_nav_id in bic_civicrm_navigationMenu() (line 131 of /home/ozk/domains/ourdomain.nl/public_html/crm/sites/all/modules/civicrm_extensions/org.project60.bic/bic.php).
Notice: Undefined variable: new_nav_id in bic_civicrm_navigationMenu() (line 122 of /home/ozk/domains/ourdomain.nl/public_html/crm/sites/all/modules/civicrm_extensions/org.project60.bic/bic.php).

**Comment by magnolia61** [comment]
I do not know about other people but my notice logs in drupal really get filled with loads of messages on the bic menu. Aside of a solution I wonder if anyone encounters the same.

![image](https://cloud.githubusercontent.com/assets/2195908/5852811/c90cff94-a21c-11e4-9b88-1f9c01e45da3.png)

**Comment by systopia** [comment]
@magnolia61  Thanks. I will take care of this once CiviSEPA 1.1 is in test
