### ISSUE TITLE
PHP8 Compatibility

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.bic#64]

**Comment by bjendres** [comment]
@cray146 Could you verify that https://github.com/Project60/org.project60.bic/releases/tag/1.8.0-alpha1 works for you?

**Comment by cray146** [comment]
I've installed this release on a fresh setup and can confirm that everything works as expected. The PHP version used was PHP 8.0.3.

**Comment by bjendres** [comment]
> I've installed this release on a fresh setup and can confirm that everything works as expected. The PHP version used was PHP 8.0.3.

Great, thanks a lot. I'll release a beta version soon.
