### ISSUE TITLE
Error "Update Problem"

### ISSUE THREAD

**Issue by maxhaslbeck** [Project60/org.project60.bic#69]
When using "Little BIC" extension version 1.8.0 I observed the following error when updating the available banks from yourwebsite.tld/civicrm/bicImport/ (or alternatively `Administer >  administration console > "Bank Information (BIC)") after clicking "update":

![grafik](https://github.com/Project60/org.project60.bic/assets/1205132/73743652-6cb5-4e70-9831-ca2dbb52309e)

"Update Problem - Das Update wurde wegen Zeitüberschreitung abgebrochen. Es macht allerdings Sinn, es einfach noch einmal zu versuchen"

**Comment by maxhaslbeck** [comment]
As version 1.8.0. requires PHP 8.0 (for PHPExcel I guess?), some timeout was hit.

**Comment by bjendres** [comment]
thanks
