### ISSUE TITLE
Undefined index: description in civicrm_api3_bic_get()

### ISSUE THREAD

**Issue by magnolia61** [Project60/org.project60.bic#9]
Hello,
Another small notice. Small but obviously good to look at.

Notice: Undefined index: description in civicrm_api3_bic_get() (line 103 of /home/ozk/domains/ourdomain/public_html/crm/sites/all/modules/civicrm_extensions/org.project60.bic/api/v3/Bic.php).

**Comment by systopia** [comment]
Thanks

**Comment by systopia** [comment]
@magnolia61 should be fixed now, please double check and re-open ticket if you still experience problems.
